# Generated by Django 4.0 on 2022-08-16 09:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('InstructorId', models.AutoField(primary_key=True, serialize=False)),
                ('InstructorName', models.CharField(max_length=100)),
                ('InstructorEmailId', models.EmailField(max_length=500, unique=True)),
                ('InstructorMobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('InstructorPhoto', models.FileField(upload_to='Instructor//Profile//1')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=100)),
                ('studentEmailId', models.EmailField(max_length=254, unique=True)),
                ('studentDOB', models.DateField()),
                ('studentProfile', models.FileField(upload_to='Student//Profile//1')),
                ('studentMobileNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
                ('Instructor', models.ForeignKey(blank=True, db_column='_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('enrolledStudents', models.ManyToManyField(to='LMS.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.subject')),
            ],
        ),
    ]
